package com.agent.baki.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity class representing a Code Fix in the system
 * 
 * Maps to the 'fix' table in the database
 * Tracks code issues identified from log analysis with exact code location
 * 
 * Key Features:
 * - Deduplication: Multiple incidents can link to the same fix if they have the same code location
 * - Status Tracking: Tracks fix lifecycle from PENDING to RESOLVED
 * - Code Location: Stores exact class name and line number where issue occurs
 * 
 * Relationships:
 * - Many-to-One with Application: Each fix belongs to one application
 * - One-to-Many with Mail: A fix can be linked to multiple email incidents
 * - One-to-Many with Jira: A fix can be linked to multiple Jira incidents
 * 
 * @author Team Baki
 */
@Entity
@Table(name = "fix", indexes = {
    @Index(name = "idx_fix_code_location", columnList = "application_id,code_class_name,code_line"),
    @Index(name = "idx_fix_status", columnList = "issue_status")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Fix {
    
    /**
     * Primary key - Auto-generated unique identifier for the fix
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "fix_id")
    private Long fixId;
    
    /**
     * Many-to-One relationship with Application
     * Each fix belongs to exactly one application
     * Foreign key: application_id
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "application_id", nullable = false)
    private Application application;
    
    /**
     * Brief summary of the issue (max 250 characters)
     * Generated by AI analysis from log content
     * Example: "NullPointerException in user authentication flow"
     */
    @Column(name = "issue_summary", length = 250)
    private String issueSummary;
    
    /**
     * Fully qualified class name where the issue occurs
     * Example: "com.agent.baki.service.UserService"
     * Used for deduplication - same class + line = same fix
     */
    @Column(name = "code_class_name", length = 255)
    private String codeClassName;
    
    /**
     * Line number in the code where the issue occurs
     * Used for deduplication - same class + line = same fix
     * Example: 145
     */
    @Column(name = "code_line")
    private Integer codeLine;
    
    /**
     * GitHub Pull Request number or URL
     * Populated when developer marks issue as IN_PROGRESS
     * Example: "PR-123" or "https://github.com/org/repo/pull/123"
     */
    @Column(name = "github_pr", length = 255)
    private String githubPr;
    
    /**
     * Current status of the fix
     * Default: PENDING
     * Values: PENDING, IGNORED, IN_PROGRESS, DB_FIX, RESOLVED
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "issue_status", length = 50, nullable = false)
    private IssueStatus issueStatus = IssueStatus.PENDING;
    
    /**
     * Reason for the action taken (ignore, db fix, etc.)
     * Populated when developer marks issue as IGNORED or provides explanation
     * Example: "Duplicate of FIX-456" or "Not a bug, expected behavior"
     */
    @Column(name = "reason", columnDefinition = "TEXT")
    private String reason;
    
    /**
     * Change number or reference for database fixes or other changes
     * Populated when developer marks issue as DB_FIX or provides change reference
     * Example: "CHG-789" or "Migration script: V2__fix_user_table.sql"
     */
    @Column(name = "change_number", length = 100)
    private String changeNumber;
    
    /**
     * Timestamp when the fix record was created
     * Automatically set by Hibernate on insert
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    /**
     * Timestamp when the fix record was last updated
     * Automatically updated by Hibernate on any modification
     */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
    
    /**
     * One-to-Many relationship with Mail entity
     * A fix can be linked to multiple email incidents
     * Cascade: Persist and merge operations cascade to mails
     */
    @OneToMany(mappedBy = "fix", cascade = CascadeType.ALL,fetch = FetchType.EAGER)
    private List<Mail> mails = new ArrayList<>();
    
    /**
     * One-to-Many relationship with Jira entity
     * A fix can be linked to multiple Jira incidents
     * Cascade: Persist and merge operations cascade to jiras
     */
    @OneToMany(mappedBy = "fix", cascade = CascadeType.ALL,fetch = FetchType.EAGER)
    private List<Jira> jiras = new ArrayList<>();
    
    // Helper methods for bidirectional relationship management
    
    /**
     * Add a mail incident to this fix
     * Maintains bidirectional relationship
     * 
     * @param mail The mail to add
     */
    public void addMail(Mail mail) {
        mails.add(mail);
        mail.setFix(this);
    }
    
    /**
     * Remove a mail incident from this fix
     * Maintains bidirectional relationship
     * 
     * @param mail The mail to remove
     */
    public void removeMail(Mail mail) {
        mails.remove(mail);
        mail.setFix(null);
    }
    
    /**
     * Add a Jira incident to this fix
     * Maintains bidirectional relationship
     * 
     * @param jira The jira to add
     */
    public void addJira(Jira jira) {
        jiras.add(jira);
        jira.setFix(this);
    }
    
    /**
     * Remove a Jira incident from this fix
     * Maintains bidirectional relationship
     * 
     * @param jira The jira to remove
     */
    public void removeJira(Jira jira) {
        jiras.remove(jira);
        jira.setFix(null);
    }
    
    /**
     * Check if this fix matches a given code location
     * Used for deduplication logic
     * 
     * @param className The class name to check
     * @param lineNumber The line number to check
     * @return true if this fix is for the same code location
     */
    public boolean matchesCodeLocation(String className, Integer lineNumber) {
        return this.codeClassName != null && 
               this.codeClassName.equals(className) && 
               this.codeLine != null && 
               this.codeLine.equals(lineNumber);
    }
}

// Made with Bob
